// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaU_yiKx8Cuf_Uf9YdWhtTLMOhMxLoJmI',
    appId: '1:260344354631:web:86c52b8b8a3982451f9e62',
    messagingSenderId: '260344354631',
    projectId: 'vibe-94074',
    authDomain: 'vibe-94074.firebaseapp.com',
    storageBucket: 'vibe-94074.appspot.com',
    measurementId: 'G-5FXRV8RFS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChDJ8DS84qazptZjizhciXkqRxf9pGc-Q',
    appId: '1:260344354631:android:ceb02111a5839d021f9e62',
    messagingSenderId: '260344354631',
    projectId: 'vibe-94074',
    storageBucket: 'vibe-94074.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxS7wovFDxGTMLBfswLE_o2939O-NmlZU',
    appId: '1:260344354631:ios:a820ef8777aedde61f9e62',
    messagingSenderId: '260344354631',
    projectId: 'vibe-94074',
    storageBucket: 'vibe-94074.appspot.com',
    iosBundleId: 'com.example.vibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxS7wovFDxGTMLBfswLE_o2939O-NmlZU',
    appId: '1:260344354631:ios:a70db9f58db22da01f9e62',
    messagingSenderId: '260344354631',
    projectId: 'vibe-94074',
    storageBucket: 'vibe-94074.appspot.com',
    iosBundleId: 'com.example.vibe.RunnerTests',
  );
}
